-- TableauxProver
-- Copyright: Laborat'orio de Tecnologia em M'etodos Formais (TecMF)
--            Pontif'icia Universidade Cat'olica do Rio de Janeiro (PUC-Rio)
-- Author:    Bruno Lopes (bvieira@inf.puc-rio.br
--            Edward Hermann (hermann@inf.puc-rio.br))
-- Tableaux Prover is licensed under a Creative Commons Attribution 3.0 Unported License


function selectLanguage(lang)
	if lang == "en" then
		stepButtonName = "Step"
		tableauButtonName = "All"
		latexButtonName = "LaTeX"
		dotButtonName = "Dot"
		undoButtonName = "Undo"
		readFileButtonName = "Read"
		disposeButtonName = "Adjust"
		trueLabel = "T"
		falseLabel = "F"
		tableauClosedLabel = "Tableau Closed!"
		fileDisclaimer = "Generated by TableauxProver"
	elseif lang == "pt-br" then
		stepButtonName = "Passo"
		tableauButtonName = "Tableau"
		latexButtonName = "LaTeX"
		dotButtonName = "Dot"
		undoButtonName = "Desfazer"
		readFileButtonName = "Arquivo"
		disposeButtonName = "Ajustar"
		trueLabel = "V"
		falseLabel = "F"
		tableauClosedLabel = "Tableau Fechado!"
		fileDisclaimer = "Gerado pelo TableauxProver"
	end
end
